[roads]
0 = { type = 'Line', start_x = 20.0, start_y = -100.0, end_x = 20.0, end_y = 100.0 }
1 = { type = 'Turn', x = 100.0, y = 100.0, r = 80.0, start = "-1/1", end = "-1/2", dir = 'CW' }
2 = { type = 'Line', start_x = 100.0, start_y = 20.0, end_x = -100.0, end_y = 20.0 }
3 = { type = 'Turn', x =-100.0, y =-100.0, r = 120.0, start = "1/2", end = "0/2", dir = 'CCW' }

4 = { type = 'Line', end_x =-20.0, end_y = -100.0, start_x =-20.0, start_y = 100.0 }
5 = { type = 'Turn', x = 100.0, y = 100.0, r = 120.0, end = "-1/1", start = "-1/2", dir = 'CCW' }
6 = { type = 'Line', end_x = 100.0, end_y =-20.0, start_x = -100.0, start_y =-20.0 }
8 = { type = 'Turn', x =-100.0, y =-100.0, r = 80.0, end = "1/2", start = "0/2", dir = 'CW' }

[nodes]
0 = [1]
1 = [2]
2 = [3]
3 = [0]

4 = [8]
5 = [4]
6 = [5]
8 = [6]
